config/routes.rb
Pickem::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resource :fb, controller: :facebook_canvas, only: [] do
    resources :requests, controller: :facebook_apprequests, only: [:index]
  end

  namespace :fb do
    with_options(controller: :games, via: [:get, :post]) do |games|
      games.match '/', action: :upcoming
      games.match 'games/completed', action: :completed
      games.match 'games/picks', action: :picks
      [:upcoming, :completed, :picks].each do |action|
        games.match "games/#{action}/:id", action: action
      end
    end

    with_options(controller: :leaderboards) do |leaderboards|
      leaderboards.match '/leaderboards', action: :index
      leaderboards.match '/leaderboards/:id', action: :show
    end

    resources :challenges, only: [:index, :show, :update] do
      collection do
        post '/', action: :index
      end
      member do
        post '', action: :show
        post 'accept'
        post 'decline'
      end
    end
  end

  scope "sites/:site", module: 'sites' do
    namespace :fb, module: 'facebook' do
      with_options(controller: :questions, via: [:get, :post]) do |questions|
        questions.match '/', action: :upcoming
        questions.match 'questions/completed', action: :completed
        questions.match 'questions/picks', action: :picks
        [:upcoming, :completed, :picks].each do |action|
          questions.match "questions/#{action}/:id", action: action
        end
      end
      with_options(controller: :leaderboards) do |leaderboards|
        leaderboards.match 'leaderboards', action: :index
      end
      resources :answers, only: :update
    end
  end

  match '/facebook' => redirect(FB[:canvas_page]), as: :facebook

  resources :unsubscribes, only: [:create, :destroy] do
    collection do
      get '/', action: :create
    end
  end
  resources :alerts, only: :destroy

  namespace :mobile do
    constraints :subdomain => "m" do
    end

    get '/' => 'games#upcoming'
  end

  match '/style_guide' => 'welcome#style_guide'
  match '/_d/:action', controller: :debug

  resources :entries, controller: :pickem_entries, only: :update

  root :to => 'welcome#index'

end

app/controllers/unsubscribes_controller.rb
class UnsubscribesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create
  before_filter :verify_action_token

  layout 'standalone'

  def create
    @notification = Notification.find(params['n'])
    target_user.unsubscribe_from_notification(@notification)
    flash.now[:notice] = "#{target_user.email} unsubscribed from '#{@notification.description}'."
  end

  def destroy
    @notification = Notification.find(params[:id])
    target_user.subscribe_to_notification(@notification)
    flash.now[:notice] = "Re-subscribed #{target_user.email} to '#{@notification.description}'."
  end

  protected
    def target_user
      @target_user ||= FacebookUser.find params['u']
    end
    helper_method :target_user

    def verify_action_token
      unless target_user.verify_action(params['t'],
                                       action_name == 'create' ? :unsubscribe : :subscribe,
                                       {
                                         'u' => params['u'],
                                         'n' => params[:id] || params['n']
                                       })
        render status: :not_authorized, text: 'Not Authorized'
      end
    end
end

app/views/unsubscribes/create.html.erb
<%= bootstrap_alert(:info , flash[:notice]) if flash[:notice].present? %>
<%= bootstrap_alert(:error, flash[:alert ]) if flash[:alert ].present? %>

<h1>Sorry to see you go</h1>

<% if @notification %>
<p>
  Did you by chance unsubscribe by mistake?  No worries!
  <%= form_tag unsubscribe_path(id: @notification.id), method: :delete do %>
    <%= hidden_field_tag 'u', target_user.id %>
    <%= hidden_field_tag 't', target_user.sign_action(:subscribe, 'u' => target_user.id, 'n' => @notification.id) %>
    <%= button_tag 'Re-subscribe', class: "btn btn-large bt-success" %>
  <% end %>
</p>
<% end %>

app/views/unsubscribes/destroy.html.erb
<%= bootstrap_alert(:info , flash[:notice]) if flash[:notice].present? %>
<%= bootstrap_alert(:error, flash[:alert ]) if flash[:alert ].present? %>

<h1>Glad you changed your mind!</h1>

<p>
  Let's go make some picks!
  <%= button_to "Let's Play", fb_app_url, class: "btn btn-large bt-success" %>
</p>